---
version: "3.7"
services:
  serverless:
    build:
      dockerfile: docker/images/lambda-serverless/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
  python:
    build:
      dockerfile: docker/images/lambda-python/Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
