service: results
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2

layers:
  pythonlayer:
    path: layer/
    name: ${self:provider.stage}-es-commonfunctions
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - python3.7
      - python3.6
