---
service: results
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  deploymentBucket:
    name: spp-results-sandbox-serverless

layers:
  pythonlayer:
    path: layer/
    name: ${self:provider.stage}-es-common-functions
    compatibleRuntimes:  # A list of runtime environments this layer is compatible with.
      - python3.7
      - python3.6
    retain: true
